---
- name: Copy default grafana config
  copy:
    src: defaults/defaults.ini
    dest: "{{ grafana_root_path }}/conf/defaults.ini"
    mode: 0644
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"

- name: Create grafana config
  template:
    src: grafana.ini.j2
    dest: "{{ grafana_conf_file }}"
    mode: 0644
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
  notify:
    - restart grafana

- name: Create grafana datasources config
  template:
    src: grafana/datasources.yaml.j2
    dest: "{{ grafana_provisioning_datasources_path }}/datasources.yaml"
    mode: 0644
    owner: "{{ grafana_user }}"
    group: "{{ grafana_group }}"
  notify:
    - restart grafana
  when: grafana_datasources

- name: Create grafana default profile
  template:
    src: grafana-profile.sh.j2
    dest: "/etc/profile.d/grafana.sh"
    mode: 0644
    owner: root
    group: root