---
# tasks file for ansible-role-grafana
- name: Run prereqs
  include_tasks: prereqs.yml

- name: Run setup
  include_tasks: setup.yml

- name: Install grafana
  include_tasks: install.yml

- name: Setup configs
  include_tasks: config.yml

- name: Setup services
  include_tasks: service.yml

- name: Wait for services
  include_tasks: wait.yml

- name: Install plugins
  include_tasks: plugins.yml

- name: Install dashboards
  include_tasks: dashboards.yml