---
- name: Wait for Grafana availability
  wait_for:
    host: 127.0.0.1
    port: "{{ grafana_port }}"
    delay: "{{ grafana_wait_delay }}"
    sleep: "{{ grafana_wait_sleep }}"
    timeout: "{{ grafana_wait_timeout }}"
  delegate_to: "{{ inventory_hostname }}"
  become: no
